# This file holds a few functions to build different versions of the AM

function(build_posix_am_noasps name)
    build_cake("${name}.cake" SOURCES "${ARGN}")
    add_executable(${name} ${posix_c_files_noasps})
    if(${STATIC_LINKING})
        set(link_flags "-static-libgcc -static -lcrypto")
    else()
        set(link_flags "-lcrypto")
    endif()
    target_link_libraries(${name} "${name}.cake" ${link_flags})
endfunction()

function(build_posix_am name)
    build_cake("${name}.cake" SOURCES "${ARGN}")
    add_executable(${name} ${posix_c_files})
    if(${STATIC_LINKING})
        set(link_flags "-static-libgcc -static -lcrypto")
    else()
        set(link_flags "-lcrypto")
    endif()
    target_link_libraries(${name} "${name}.cake" ${link_flags})
endfunction()

function(build_posix_am_hacl name)
    build_cake("${name}.cake" SOURCES "${ARGN}")
    add_executable(${name} ${posix_c_files_hacl})
    add_hacl(${name})
    if(${STATIC_LINKING})
        set(link_flags "-static-libgcc -static")
    endif()
    target_link_libraries(${name} "${name}.cake" ${link_flags})
endfunction()

function(build_posix_am_tpm name)
    build_cake("${name}.cake" SOURCES "${ARGN}")
    add_executable(${name} ${posix_c_files_tpm})
    add_tpm(${name})
    if(${STATIC_LINKING})
        set(link_flags "-static-libgcc -static -lcrypto")
    else()
        set(link_flags "-lcrypto")
    endif()
    target_link_libraries(${name} "${name}.cake" ${link_flags})
endfunction()

